<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-17T02:31:56 GMT-05:00" name="Suite" finished-at="2025-02-17T02:32:04 GMT-05:00" duration-ms="7857">
    <groups>
    </groups>
    <test started-at="2025-02-17T02:31:56 GMT-05:00" name="Test" finished-at="2025-02-17T02:32:04 GMT-05:00" duration-ms="7857">
      <class name="com.luma.pagetests.CreateNewCustomerAccountTest">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.luma.pagetests.CreateNewCustomerAccountTest@740cae06]" started-at="2025-02-17T02:31:56 GMT-05:00" name="setUp" finished-at="2025-02-17T02:32:01 GMT-05:00" duration-ms="5443" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.luma.pagetests.CreateNewCustomerAccountTest.verifySuccessfullLogin3()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfullLogin3()[pri:0, instance:com.luma.pagetests.CreateNewCustomerAccountTest@740cae06]" started-at="2025-02-17T02:32:01 GMT-05:00" name="verifySuccessfullLogin3" finished-at="2025-02-17T02:32:03 GMT-05:00" duration-ms="2112" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Home Page] but found [Customer Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Home Page] but found [Customer Login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.luma.pagetests.CreateNewCustomerAccountTest.verifySuccessfullLogin3(CreateNewCustomerAccountTest.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfullLogin3 -->
        <test-method is-config="true" signature="end(org.testng.ITestResult)[pri:0, instance:com.luma.pagetests.CreateNewCustomerAccountTest@740cae06]" started-at="2025-02-17T02:32:03 GMT-05:00" name="end" finished-at="2025-02-17T02:32:04 GMT-05:00" duration-ms="273" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifySuccessfullLogin3 status=FAILURE method=CreateNewCustomerAccountTest.verifySuccessfullLogin3()[pri:0, instance:com.luma.pagetests.CreateNewCustomerAccountTest@740cae06] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- com.luma.pagetests.CreateNewCustomerAccountTest -->
      <class name="com.luma.pagetests.CustomerLoginTest">
        <test-method is-config="true" signature="init()[pri:0, instance:com.luma.pagetests.CustomerLoginTest@3646a422]" started-at="2025-02-17T02:31:56 GMT-05:00" name="init" finished-at="2025-02-17T02:31:56 GMT-05:00" duration-ms="214" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.luma.pagetests.CustomerLoginTest@3646a422]" started-at="2025-02-17T02:31:56 GMT-05:00" name="setUp" finished-at="2025-02-17T02:32:01 GMT-05:00" duration-ms="5161" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.luma.pagetests.CustomerLoginTest.verifySuccessfullLogin()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.luma.pagetests.CustomerLoginTest@3646a422]" started-at="2025-02-17T02:31:56 GMT-05:00" name="setUp" finished-at="2025-02-17T02:31:56 GMT-05:00" duration-ms="429" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.luma.pagetests.CustomerLoginTest.verifySuccessfullLogin2()]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[No Data is available for this testcase : verifySuccessfullLogin2]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: No Data is available for this testcase : verifySuccessfullLogin2
at com.luma.pagetests.BaseTest.getDataMap(BaseTest.java:118)
at com.luma.pagetests.BaseTest.setUp(BaseTest.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:578)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySuccessfullLogin2()[pri:0, instance:com.luma.pagetests.CustomerLoginTest@3646a422]" started-at="2025-02-17T02:31:56 GMT-05:00" name="verifySuccessfullLogin2" finished-at="2025-02-17T02:31:56 GMT-05:00" duration-ms="0" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[No Data is available for this testcase : verifySuccessfullLogin2]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: No Data is available for this testcase : verifySuccessfullLogin2
at com.luma.pagetests.BaseTest.getDataMap(BaseTest.java:118)
at com.luma.pagetests.BaseTest.setUp(BaseTest.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:578)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfullLogin2 -->
        <test-method is-config="true" signature="end(org.testng.ITestResult)[pri:0, instance:com.luma.pagetests.CustomerLoginTest@3646a422]" started-at="2025-02-17T02:31:56 GMT-05:00" name="end" finished-at="2025-02-17T02:31:56 GMT-05:00" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifySuccessfullLogin2 status=SKIP method=CustomerLoginTest.verifySuccessfullLogin2()[pri:0, instance:com.luma.pagetests.CustomerLoginTest@3646a422] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method signature="verifySuccessfullLogin()[pri:0, instance:com.luma.pagetests.CustomerLoginTest@3646a422]" started-at="2025-02-17T02:32:01 GMT-05:00" name="verifySuccessfullLogin" finished-at="2025-02-17T02:32:03 GMT-05:00" duration-ms="2156" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Home Page] but found [Customer Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Home Page] but found [Customer Login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.luma.pagetests.CustomerLoginTest.verifySuccessfullLogin(CustomerLoginTest.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfullLogin -->
        <test-method is-config="true" signature="end(org.testng.ITestResult)[pri:0, instance:com.luma.pagetests.CustomerLoginTest@3646a422]" started-at="2025-02-17T02:32:03 GMT-05:00" name="end" finished-at="2025-02-17T02:32:03 GMT-05:00" duration-ms="324" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifySuccessfullLogin status=FAILURE method=CustomerLoginTest.verifySuccessfullLogin()[pri:0, instance:com.luma.pagetests.CustomerLoginTest@3646a422] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.luma.pagetests.CustomerLoginTest@3646a422]" started-at="2025-02-17T02:32:04 GMT-05:00" name="tearDown" finished-at="2025-02-17T02:32:04 GMT-05:00" duration-ms="314" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.luma.pagetests.CustomerLoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
